name: Hello from the script

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Hello from the script      
        run: sh .github/scripts/script.sh
        env: 
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
