name: Hello from the script

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          ls -lha
          ls -la .github/scripts
          ls -la .github/scripts/script.sh
          
      - name: Hello from the script      
        run: .github/scripts/script.sh
        shell: bash
        env: 
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
